# Generated by Django 2.2 on 2021-06-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newarrivals',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
